baseline:
    locate_type: all_in_one
    model: ''
    prediction_type: all_in_one
    shot_num: 0
    type: ''
batch_size: 1
config: config.yaml
dataset: ''
dev: false
device: cuda
energynet:
    decomposition: 'no'
    epoch: 15
    fine_tuning_epoch: 30
    loss_con_incon_ordering: false
    loss_fully_separate: false
    loss_incon_incon_ordering: false
    loss_subset_ordering: false
    loss_type: triplet
    lr: 1.0e-06
    many_pos_vs_one_neg: false
    one_pos_vs_many_neg: false
    output_form: real_num
    repre_model: roberta
    supervised:
        loss: CE
    triplet:
        fully_separate_margin: 0.001
        margin: 0.1
    weight_con_incon_ordering: 0.1
    weight_fully_separate: 0.1
    weight_incon_incon_ordering: 0.1
    weight_subset_ordering: 0.01
eval:
    batch_size: 1
    pairwise: arbitrary_pairs
extra_for_eval: ''
finetune_job_id: 0
folder_path: ''
job_id: 0
lconvqa:
    stepwise_dataset_eval2_num: 200
    stepwise_dataset_eval_num: 200
    stepwise_dataset_test_num: 200
    stepwise_dataset_train_num: 6754
locate:
    agg_method: avg
    attentions_num_layer: 7
    select_method: recursive_max
    type: attention
model_path: ''
pairwise: arbitrary_pairs
scratch: false
seed: 1014
set_nli:
    stepwise_dataset_eval2_num: 200
    stepwise_dataset_eval_num: 200
    stepwise_dataset_test_num: 200
    stepwise_dataset_train_num: 6227
task: ''
time_key: ''
