energynet:
  base_model: roberta-large
  output_form: 2dim_vec
  energy_col: 1
  label_column: binary_labels
  batch_size: 16
  num_epochs: 3
  optimizer: adamw
  max_lr: 1e-5
  weight_decay: 0.03
  loss: binary_cross_entropy
  add_ranking_loss: true
  add_ranking_loss_setting: 3
  add_train_data: true
  margin: 1
  eval_every: 100
  mixing_weights: 0.9, 0.1
  binary_loader: balanced
  ckpt_save_path: models/nli
  dataset_path: data/nli/snli_mnli_anli_train_dev_with_finegrained.jsonl

locate:
  type: gradnorm

device: cuda