energynet:
  base_model: roberta-large
  output_form: 3dim_vec
  energy_col: 2
  label_column: original_labels
  batch_size: 16
  num_epochs: 3
  max_lr: 1e-5
  weight_decay: 0.03
  loss: cross_entropy
  add_ranking_loss: false
  add_train_data: true
  margin: 1
  eval_every: 100
  ckpt_save_path: models/nli
  dataset_path: data/nli/snli_mnli_anli_train_dev_with_finegrained.jsonl

locate:
  type: gradnorm

device: cuda